sudo: required

services:
  - docker

script:
  - docker build -t appium-base base/.
  - docker build -t android android/.
  - docker build -t appium appium/.
  - docker run -d --name appium-base appium-base
  - docker run -d --name appium-node appium
  - docker run -d --name android-avd appium
  - docker ps
  - docker exec appium-node /bin/sh -c "appium-doctor --android"
  - docker exec android-avd /bin/sh -c "android list"
  - docker exec android-avd /bin/sh -c "adb devices"
